#!/bin/bash

function yumInstall() {
    # Install packages from $pkgFile
    echo "Installing security updates..."
    while read -r package; do
        echo "Updating $package"
        # Redirect stderr to stdout and filter out annoying warnings about
        # deltarpms plus false positives about missing arguments
        yum -q -y update "$package" 2>&1 | grep -E -v '(delta|argument)'
    done < "$pkgFile"
    exit 0
}

this="centos-yum-security"

usage="$this [-d] [-h] [-y]"

helptext="
$usage

Emulate the yum --security plugin for CentOS 7.
Basically a wrapper around 'centos-package-cron' (https://github.com/wied03/centos-package-cron)

Switches:
-h: Show this help then exit
-d: Dry run. Only show information and exit. Do not prompt to install anything.
-y: Assume yes. Do not prompt before installing security updates.

Exit codes:
1: Error. Need to be root
2: Error. Missing package 'centos-package-cron'
3: Error. Incorrect switch
50: Ok. No security updates available.
100: Ok. Security updates available.
0: Ok. (Clean exit)

Author of $this: 
Magnus Wallin <magnus.wallin@tutanota.com>

License of $this:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Author of centos-package-cron:
Brady Wied <https://github.com/wied03>
License for centos-package-cron:
Copyright (c) 2016, BSW Technology Consulting LLC All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:

· Redistributions of source code must retain the above copyright notice, this list of conditions and the 
following disclaimer.

· Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the 
following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED 
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY 
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF 
SUCH DAMAGE.
"

dryRun=""
assumeYes=""

# Get command line args
while getopts ":dhy" opt; do
    case $opt in
        d)
            dryRun="true"
            ;;
        h)
            echo "$helptext" | less
            exit 0
            ;;
        y)
            assumeYes="true"
            ;;
        *)
            echo -e "Unknown option. '-d', '-y' and '-h' allowed. Usage:\\n$usage"
            exit 3
            ;;
    esac
done

shift $(($OPTIND-1))

if ! command -v centos-package-cron &> /dev/null; then
    echo "'centos-package-cron' not installed. 
See: https://github.com/wied03/centos-package-cron for instructions"
    exit 2
fi

if [[ $EUID != 0 ]]; then
    echo "You need to be root. Exiting"
    exit 1
fi

# Save package information here
pkgFile="/root/centos-sec-updates"

# Gather information about packages needed for security. Write to $pkgFile
echo "Gathering information about packages needed for security. This will take a while..."
centos-package-cron --output stdout --forceold | sed -nE '/.*http.*$/! s/^\* (.*$)/\1/p' | grep -E -v '[MWTFS][a-z]{2} [FDJSNAOM][a-z]{2} ' | sort -u > "$pkgFile"

# Check if we have content in $pkgFile
packages=$(wc -l "$pkgFile" | awk '{ print $1 }')

if (( "$packages" < 1 )); then
    echo "No packages needed for security"
    exit 50
else
    echo "$packages packages needed for security:"
    cat "$pkgFile"
    if [[ "$dryRun" == "true" ]]; then
        exit 100
    fi
    if [[ "$assumeYes" == "true" ]]; then
        yumInstall
    fi
fi

while true; do
    read -p "Install updates? [Y/N] " yn
    case "$yn" in
        [Yy])
            yumInstall
            ;;
        [Nn])
            echo "Aborting. List of packages saved in $pkgFile"
            exit 100
            ;;
        *)
            echo "Incorrect input."
    esac
done
